### get all available notes
GET http://localhost:3001/api/notes

### find specific note
GET http://localhost:3001/api/notes/622e0c054f0841ad3ac375a9

### delete specific note
DELETE http://localhost:3001/api/notes/622e0c054f0841ad3ac375a9

### add new notes
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "apple is the best company",
    "important": true
}

### update notes
PUT http://localhost:3001/api/notes/622d9029e4975892b7ac0f61
Content-Type: application/json

{
    "content": "Postman is not Bekman",
    "important": false
}